# Generated by Django 5.1.7 on 2025-03-24 08:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_tripbill_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripbill',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
