# Generated by Django 5.1.7 on 2025-03-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('survey_location', models.CharField(max_length=255)),
                ('start_odometer', models.IntegerField()),
                ('camera_position', models.CharField(choices=[('front', 'Front'), ('back', 'Back')], max_length=10)),
                ('reason_for_not_starting', models.TextField(blank=True, null=True)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('end_odometer', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
